sudo: false
language: node_js
node_js:
- '0.12'
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install compass
- grunt build
- ls -altr
deploy:
  provider: s3
  access_key_id: AKIAIO7M4ARWYBM65G4Q
  secret_access_key:
    secure: bJvc87EHh5Xey+1A4oc/52gZHPrimIJFk+xUEPQTQMFRwi7UB7RRbSRwRFeWUo+iXqloJdjYfSi4HDoMJNvHQF8wLVjUUGREjd1zBLm9/iYmrW+lu31rOze0ZJDG5IdAI/LgK9OlkSxqnzqULJ8DBPZEVXdQyMjAqjEAVbCpZRnQUDDMnTXfbO+kIzZTEEwzAWSTqea/WaCmCNl57afTLqooze/YFN+GSVepOxIuNd5RtqtDsx4PuiLRny7JAkTl9FQzuZYEfUUxZYcvva+NQmwsjSh2PvncGnDVhI30ngw98UzwLgiNocAuqghZzTd/c1XYUaq03UGsJF0jpQZj5cIQ+e5u34TX9jfhoaNh6Fxmgxas0dA2/z9JCe2ctI2jicYyloegUTBes2JJ/49ux7Wi6Buc7PZxQCF9xT9iZTVTEgjMRMutyLikhawlSW/C4jwasKZQ+AT9s74WwDTISISYiAR5CavtVvQOXcVDDaLrR6De1EC3V+fRHast/pn19MNdvdCdxsB++EUPTzDrX2EVkr7zZIuRw91zi1Xau01l/F3wCvC1pjO/tiaE7i7ghYsWWZ3WR+wV7HisjqfGT1fA6f5a0/Lr+q83EOPQzq3Qb6ESVleoMVxcvStcqF/KWdl1qZZ3AP0RDFQX7W/3OB0y/uDWUeH71vVJeYKyWHU=
  bucket: parc.brntgarlic.com
  local-dir: dist
  acl: public_read
